[package]
name = "tstools"
version = "0.1.0"
authors = ["toshi_pp <toshiq2@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.1"
lazy_static = "1.1.0"
log = "0.4"
env_logger = "0.5.13"
jisx0213 = { path = "jisx0213" }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
tokio = "0.1"
bytes = "0.4"
tokio-channel = "0.1"
futures = "0.1"
structopt = "0.2"

[workspace]
members = [
       "jisx0213",
]
