version: 2
jobs:
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run: |
          cargo install cargo-audit
          cargo audit -D
      - run: cargo test --all

workflows:
  version: 2
  ci:
    jobs:
      - test
