name: ci
on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:bullseye
    steps:
      - uses: actions/checkout@v3
      - run: cargo install cargo-audit
      - run: cargo audit --ignore RUSTSEC-2020-0071
      - run: cargo test --all
